#!/bin/bash


echo Script creado por NZ-Creaciones para cambiar la dirección mac automaticamente
echo
echo

echo ..dentro de 4 seg se inicia el script patrocinado por NZ-Creaciones


echo
echo


sleep 4s


echo desactivando interfaz Wlan0
echo

ifconfig wlan0 down


echo Cambiar dirección MAC en modo automático
echo
echo
macchanger -a wlan0


echo
echo

echo Volviendo a levantar la interfaz Wlan0

ifconfig wlan0 up
echo
echo
echo
echo
echo Todo ha terminado correcto, NZ-Creaciones te ayudó con este script
