#!/bin/bash

echo ..dentro de 4 seg se inicia el script patrocinado por NZ-Creaciones
sleep 4s

echo
echo
echo
echo            “SELECCIONE UNA OPCION”
echo
echo
echo “1 Cambiar MAC interfaz Wlan0”

echo “2 Cambiar MAC modo Monitor Wlan0”

echo “3 Cambiar MAC interfaz Wlan1”

echo “4 Cambiar MAC modo Monitor Wlan1”

echo “5 Quitar todas las interfaces modo monitor”

echo “6 SALIR”

echo
echo Elegir una opcion
read opcion
case $opcion

1)echo Cambiar MAC Wlan0:; man /home/nerviozzo/scripts/Wlan0

2)echo introduzca el nombre del archivo a modificar los permisos:; read archivo1; ls –la $archivo1; echo seleccione los permisos que desea establecer:; read permisos; chmod $permisos $archivos1; ls –la $archivo1;;

3)clear; echo introduzca la cadena de valores a buscar; read cadena; echo introduzca el archivo en el cual se va a buscar la cadena read archivo2; grep $cadena $archivo2;;

4)clear; echo introduzca el nombre del comando que desee ver la ayuda:; read comando; man $comando;;

5)exit;;

*)echo seleccione una opcion valida de la lista;;
esac
echo ¿Desea realizar otra opcion? Si No
read otra
case $otra in

Si)./scriptmenu;;

No) clear;;
esac

